workspace(name = "test")

local_repository(
    name = "com_github_schoppmp_rules_oblivc",
    path = "..",
)

load(
    "@com_github_schoppmp_rules_oblivc//oblivc:preload.bzl",
    "oblivc_deps_preload",
)

oblivc_deps_preload()

load("@com_github_schoppmp_rules_oblivc//oblivc:deps.bzl", "oblivc_deps")

oblivc_deps()
